language: ruby
rvm:
- 2.0.0
env:
  matrix:
  - DB=mysql
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake
before_script:
- cp config/database.travis.yml config/database.yml
- mysql -e 'create database saveling_test'
notifications:
  hipchat:
    rooms:
      secure: aR5wCrU3yTjgL6sROlgNeC9NAiZzyavon0tqSS+Gus5cxMIiiMHZi7Gcg/bdS0OjEl8w1MXKFnCvdaPDj11UzonXM4IJBwnrhwOOqkbT6yNHrCLS+/rFQikUfDkcotCh5Ut5TacF0jVsVjNr12Qunpgry8lPY52EH8qBDiKD7Nw=
