language: ruby
rvm:
- 2.0.0
env:
  matrix:
  - DB=mysql
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake
before_script:
- cp config/database.travis.yml config/database.yml
- mysql -e 'create database saveling_test'
notifications:
  hipchat:
  - secure: "gRoCJVyeVbcDngdnka67SNAR8q8fVqV50Frv2TeGmSdhPOnrtqiVUGTeXbXYzmwIBCAH+ZzHfvC6mquUWMZx8j7M/g+egk0trIgU2R6TD1f1ofGBiYh/oI5HaXw76zIjJXaxUkMv7bmG4UKnnsXkFTGJuwQgOtbkh1GT/o3Nphk="
